from config import (
    FUNDAMENTALS_PATH,
    SELECTION_CLUSTER_COUNT,
    SELECTION_CORRELATION_WEIGHT,
    SELECTION_DIVERSIFICATION_PENALTY,
    SELECTION_FEATURE_WEIGHT,
    SELECTION_LOOKBACK_WEEKS,
    SELECTION_MIN_CLUSTER_SIZE,
    SELECTION_MIN_SAMPLES,
    SELECTION_OUTPUT_DIR,
    SELECTION_TARGET_COUNT,
)


def test_selection_experiment_constants_are_preregistered():
    assert FUNDAMENTALS_PATH.name == "fundamentals_point_in_time.csv"
    assert SELECTION_OUTPUT_DIR.name == "selection_experiment"
    assert SELECTION_TARGET_COUNT == 12
    assert SELECTION_CLUSTER_COUNT == 6
    assert SELECTION_LOOKBACK_WEEKS == 104
    assert SELECTION_MIN_CLUSTER_SIZE == 3
    assert SELECTION_MIN_SAMPLES == 3
    assert SELECTION_FEATURE_WEIGHT == 0.50
    assert SELECTION_CORRELATION_WEIGHT == 0.50
    assert SELECTION_DIVERSIFICATION_PENALTY == 0.25
